// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"event-service/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewEventRepository creates a new instance of EventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventRepository {
	mock := &EventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EventRepository is an autogenerated mock type for the EventRepository type
type EventRepository struct {
	mock.Mock
}

type EventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *EventRepository) EXPECT() *EventRepository_Expecter {
	return &EventRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type EventRepository
func (_mock *EventRepository) Create(event *model.Event) (*int64, error) {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.Event) (*int64, error)); ok {
		return returnFunc(event)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.Event) *int64); ok {
		r0 = returnFunc(event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.Event) error); ok {
		r1 = returnFunc(event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type EventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - event *model.Event
func (_e *EventRepository_Expecter) Create(event interface{}) *EventRepository_Create_Call {
	return &EventRepository_Create_Call{Call: _e.mock.On("Create", event)}
}

func (_c *EventRepository_Create_Call) Run(run func(event *model.Event)) *EventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Event
		if args[0] != nil {
			arg0 = args[0].(*model.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EventRepository_Create_Call) Return(n *int64, err error) *EventRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *EventRepository_Create_Call) RunAndReturn(run func(event *model.Event) (*int64, error)) *EventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type EventRepository
func (_mock *EventRepository) Delete(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type EventRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *EventRepository_Expecter) Delete(id interface{}) *EventRepository_Delete_Call {
	return &EventRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *EventRepository_Delete_Call) Run(run func(id int64)) *EventRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EventRepository_Delete_Call) Return(err error) *EventRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventRepository_Delete_Call) RunAndReturn(run func(id int64) error) *EventRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type EventRepository
func (_mock *EventRepository) GetAll() ([]*model.Event, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*model.Event, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*model.Event); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EventRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type EventRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *EventRepository_Expecter) GetAll() *EventRepository_GetAll_Call {
	return &EventRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *EventRepository_GetAll_Call) Run(run func()) *EventRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventRepository_GetAll_Call) Return(events []*model.Event, err error) *EventRepository_GetAll_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *EventRepository_GetAll_Call) RunAndReturn(run func() ([]*model.Event, error)) *EventRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type EventRepository
func (_mock *EventRepository) GetByID(id int64) (*model.Event, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*model.Event, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *model.Event); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EventRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type EventRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *EventRepository_Expecter) GetByID(id interface{}) *EventRepository_GetByID_Call {
	return &EventRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *EventRepository_GetByID_Call) Run(run func(id int64)) *EventRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EventRepository_GetByID_Call) Return(event *model.Event, err error) *EventRepository_GetByID_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *EventRepository_GetByID_Call) RunAndReturn(run func(id int64) (*model.Event, error)) *EventRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type EventRepository
func (_mock *EventRepository) Update(event *model.Event) error {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Event) error); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type EventRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - event *model.Event
func (_e *EventRepository_Expecter) Update(event interface{}) *EventRepository_Update_Call {
	return &EventRepository_Update_Call{Call: _e.mock.On("Update", event)}
}

func (_c *EventRepository_Update_Call) Run(run func(event *model.Event)) *EventRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Event
		if args[0] != nil {
			arg0 = args[0].(*model.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EventRepository_Update_Call) Return(err error) *EventRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventRepository_Update_Call) RunAndReturn(run func(event *model.Event) error) *EventRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
