// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"booking-service/internal/client"

	mock "github.com/stretchr/testify/mock"
)

// NewEventGetter creates a new instance of EventGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventGetter {
	mock := &EventGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EventGetter is an autogenerated mock type for the EventGetter type
type EventGetter struct {
	mock.Mock
}

type EventGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *EventGetter) EXPECT() *EventGetter_Expecter {
	return &EventGetter_Expecter{mock: &_m.Mock}
}

// GetEvent provides a mock function for the type EventGetter
func (_mock *EventGetter) GetEvent(eventID int64) (*client.Event, error) {
	ret := _mock.Called(eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 *client.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*client.Event, error)); ok {
		return returnFunc(eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *client.Event); ok {
		r0 = returnFunc(eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EventGetter_GetEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvent'
type EventGetter_GetEvent_Call struct {
	*mock.Call
}

// GetEvent is a helper method to define mock.On call
//   - eventID int64
func (_e *EventGetter_Expecter) GetEvent(eventID interface{}) *EventGetter_GetEvent_Call {
	return &EventGetter_GetEvent_Call{Call: _e.mock.On("GetEvent", eventID)}
}

func (_c *EventGetter_GetEvent_Call) Run(run func(eventID int64)) *EventGetter_GetEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EventGetter_GetEvent_Call) Return(event *client.Event, err error) *EventGetter_GetEvent_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *EventGetter_GetEvent_Call) RunAndReturn(run func(eventID int64) (*client.Event, error)) *EventGetter_GetEvent_Call {
	_c.Call.Return(run)
	return _c
}
