// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"booking-service/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewBookingRepository creates a new instance of BookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingRepository {
	mock := &BookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BookingRepository is an autogenerated mock type for the BookingRepository type
type BookingRepository struct {
	mock.Mock
}

type BookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BookingRepository) EXPECT() *BookingRepository_Expecter {
	return &BookingRepository_Expecter{mock: &_m.Mock}
}

// CountConfirmedByEventID provides a mock function for the type BookingRepository
func (_mock *BookingRepository) CountConfirmedByEventID(eventID int64) (int64, error) {
	ret := _mock.Called(eventID)

	if len(ret) == 0 {
		panic("no return value specified for CountConfirmedByEventID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (int64, error)); ok {
		return returnFunc(eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = returnFunc(eventID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BookingRepository_CountConfirmedByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountConfirmedByEventID'
type BookingRepository_CountConfirmedByEventID_Call struct {
	*mock.Call
}

// CountConfirmedByEventID is a helper method to define mock.On call
//   - eventID int64
func (_e *BookingRepository_Expecter) CountConfirmedByEventID(eventID interface{}) *BookingRepository_CountConfirmedByEventID_Call {
	return &BookingRepository_CountConfirmedByEventID_Call{Call: _e.mock.On("CountConfirmedByEventID", eventID)}
}

func (_c *BookingRepository_CountConfirmedByEventID_Call) Run(run func(eventID int64)) *BookingRepository_CountConfirmedByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BookingRepository_CountConfirmedByEventID_Call) Return(n int64, err error) *BookingRepository_CountConfirmedByEventID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *BookingRepository_CountConfirmedByEventID_Call) RunAndReturn(run func(eventID int64) (int64, error)) *BookingRepository_CountConfirmedByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBooking provides a mock function for the type BookingRepository
func (_mock *BookingRepository) CreateBooking(booking *model.Booking) error {
	ret := _mock.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Booking) error); ok {
		r0 = returnFunc(booking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BookingRepository_CreateBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBooking'
type BookingRepository_CreateBooking_Call struct {
	*mock.Call
}

// CreateBooking is a helper method to define mock.On call
//   - booking *model.Booking
func (_e *BookingRepository_Expecter) CreateBooking(booking interface{}) *BookingRepository_CreateBooking_Call {
	return &BookingRepository_CreateBooking_Call{Call: _e.mock.On("CreateBooking", booking)}
}

func (_c *BookingRepository_CreateBooking_Call) Run(run func(booking *model.Booking)) *BookingRepository_CreateBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Booking
		if args[0] != nil {
			arg0 = args[0].(*model.Booking)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BookingRepository_CreateBooking_Call) Return(err error) *BookingRepository_CreateBooking_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BookingRepository_CreateBooking_Call) RunAndReturn(run func(booking *model.Booking) error) *BookingRepository_CreateBooking_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEventAndUID provides a mock function for the type BookingRepository
func (_mock *BookingRepository) ExistsByEventAndUID(eventID int64, uid uuid.UUID) (bool, error) {
	ret := _mock.Called(eventID, uid)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEventAndUID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, uuid.UUID) (bool, error)); ok {
		return returnFunc(eventID, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, uuid.UUID) bool); ok {
		r0 = returnFunc(eventID, uid)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, uuid.UUID) error); ok {
		r1 = returnFunc(eventID, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BookingRepository_ExistsByEventAndUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEventAndUID'
type BookingRepository_ExistsByEventAndUID_Call struct {
	*mock.Call
}

// ExistsByEventAndUID is a helper method to define mock.On call
//   - eventID int64
//   - uid uuid.UUID
func (_e *BookingRepository_Expecter) ExistsByEventAndUID(eventID interface{}, uid interface{}) *BookingRepository_ExistsByEventAndUID_Call {
	return &BookingRepository_ExistsByEventAndUID_Call{Call: _e.mock.On("ExistsByEventAndUID", eventID, uid)}
}

func (_c *BookingRepository_ExistsByEventAndUID_Call) Run(run func(eventID int64, uid uuid.UUID)) *BookingRepository_ExistsByEventAndUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BookingRepository_ExistsByEventAndUID_Call) Return(b bool, err error) *BookingRepository_ExistsByEventAndUID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *BookingRepository_ExistsByEventAndUID_Call) RunAndReturn(run func(eventID int64, uid uuid.UUID) (bool, error)) *BookingRepository_ExistsByEventAndUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsByEventID provides a mock function for the type BookingRepository
func (_mock *BookingRepository) GetBookingsByEventID(eventID int64) ([]*model.Booking, error) {
	ret := _mock.Called(eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByEventID")
	}

	var r0 []*model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]*model.Booking, error)); ok {
		return returnFunc(eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []*model.Booking); ok {
		r0 = returnFunc(eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BookingRepository_GetBookingsByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsByEventID'
type BookingRepository_GetBookingsByEventID_Call struct {
	*mock.Call
}

// GetBookingsByEventID is a helper method to define mock.On call
//   - eventID int64
func (_e *BookingRepository_Expecter) GetBookingsByEventID(eventID interface{}) *BookingRepository_GetBookingsByEventID_Call {
	return &BookingRepository_GetBookingsByEventID_Call{Call: _e.mock.On("GetBookingsByEventID", eventID)}
}

func (_c *BookingRepository_GetBookingsByEventID_Call) Run(run func(eventID int64)) *BookingRepository_GetBookingsByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BookingRepository_GetBookingsByEventID_Call) Return(bookings []*model.Booking, err error) *BookingRepository_GetBookingsByEventID_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *BookingRepository_GetBookingsByEventID_Call) RunAndReturn(run func(eventID int64) ([]*model.Booking, error)) *BookingRepository_GetBookingsByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsByUID provides a mock function for the type BookingRepository
func (_mock *BookingRepository) GetBookingsByUID(uid uuid.UUID) ([]*model.Booking, error) {
	ret := _mock.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByUID")
	}

	var r0 []*model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]*model.Booking, error)); ok {
		return returnFunc(uid)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []*model.Booking); ok {
		r0 = returnFunc(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BookingRepository_GetBookingsByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsByUID'
type BookingRepository_GetBookingsByUID_Call struct {
	*mock.Call
}

// GetBookingsByUID is a helper method to define mock.On call
//   - uid uuid.UUID
func (_e *BookingRepository_Expecter) GetBookingsByUID(uid interface{}) *BookingRepository_GetBookingsByUID_Call {
	return &BookingRepository_GetBookingsByUID_Call{Call: _e.mock.On("GetBookingsByUID", uid)}
}

func (_c *BookingRepository_GetBookingsByUID_Call) Run(run func(uid uuid.UUID)) *BookingRepository_GetBookingsByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BookingRepository_GetBookingsByUID_Call) Return(bookings []*model.Booking, err error) *BookingRepository_GetBookingsByUID_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *BookingRepository_GetBookingsByUID_Call) RunAndReturn(run func(uid uuid.UUID) ([]*model.Booking, error)) *BookingRepository_GetBookingsByUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type BookingRepository
func (_mock *BookingRepository) GetByID(id int64) (*model.Booking, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*model.Booking, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *model.Booking); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BookingRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type BookingRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *BookingRepository_Expecter) GetByID(id interface{}) *BookingRepository_GetByID_Call {
	return &BookingRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *BookingRepository_GetByID_Call) Run(run func(id int64)) *BookingRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BookingRepository_GetByID_Call) Return(booking *model.Booking, err error) *BookingRepository_GetByID_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *BookingRepository_GetByID_Call) RunAndReturn(run func(id int64) (*model.Booking, error)) *BookingRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
