// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewQueueRepository creates a new instance of QueueRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueueRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueueRepository {
	mock := &QueueRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QueueRepository is an autogenerated mock type for the QueueRepository type
type QueueRepository struct {
	mock.Mock
}

type QueueRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *QueueRepository) EXPECT() *QueueRepository_Expecter {
	return &QueueRepository_Expecter{mock: &_m.Mock}
}

// Dequeue provides a mock function for the type QueueRepository
func (_mock *QueueRepository) Dequeue(ctx context.Context, eventID int64, timeout time.Duration) (string, error) {
	ret := _mock.Called(ctx, eventID, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Dequeue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Duration) (string, error)); ok {
		return returnFunc(ctx, eventID, timeout)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, time.Duration) string); ok {
		r0 = returnFunc(ctx, eventID, timeout)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, time.Duration) error); ok {
		r1 = returnFunc(ctx, eventID, timeout)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QueueRepository_Dequeue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dequeue'
type QueueRepository_Dequeue_Call struct {
	*mock.Call
}

// Dequeue is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
//   - timeout time.Duration
func (_e *QueueRepository_Expecter) Dequeue(ctx interface{}, eventID interface{}, timeout interface{}) *QueueRepository_Dequeue_Call {
	return &QueueRepository_Dequeue_Call{Call: _e.mock.On("Dequeue", ctx, eventID, timeout)}
}

func (_c *QueueRepository_Dequeue_Call) Run(run func(ctx context.Context, eventID int64, timeout time.Duration)) *QueueRepository_Dequeue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *QueueRepository_Dequeue_Call) Return(s string, err error) *QueueRepository_Dequeue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *QueueRepository_Dequeue_Call) RunAndReturn(run func(ctx context.Context, eventID int64, timeout time.Duration) (string, error)) *QueueRepository_Dequeue_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function for the type QueueRepository
func (_mock *QueueRepository) Enqueue(ctx context.Context, eventID int64, payload string) error {
	ret := _mock.Called(ctx, eventID, payload)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, eventID, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QueueRepository_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type QueueRepository_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
//   - payload string
func (_e *QueueRepository_Expecter) Enqueue(ctx interface{}, eventID interface{}, payload interface{}) *QueueRepository_Enqueue_Call {
	return &QueueRepository_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, eventID, payload)}
}

func (_c *QueueRepository_Enqueue_Call) Run(run func(ctx context.Context, eventID int64, payload string)) *QueueRepository_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *QueueRepository_Enqueue_Call) Return(err error) *QueueRepository_Enqueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QueueRepository_Enqueue_Call) RunAndReturn(run func(ctx context.Context, eventID int64, payload string) error) *QueueRepository_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}
