// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"booking-service/internal/repository"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewSeatRepository creates a new instance of SeatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSeatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SeatRepository {
	mock := &SeatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SeatRepository is an autogenerated mock type for the SeatRepository type
type SeatRepository struct {
	mock.Mock
}

type SeatRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SeatRepository) EXPECT() *SeatRepository_Expecter {
	return &SeatRepository_Expecter{mock: &_m.Mock}
}

// Decrement provides a mock function for the type SeatRepository
func (_mock *SeatRepository) Decrement(ctx context.Context, eventID int64) (int64, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for Decrement")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SeatRepository_Decrement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrement'
type SeatRepository_Decrement_Call struct {
	*mock.Call
}

// Decrement is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
func (_e *SeatRepository_Expecter) Decrement(ctx interface{}, eventID interface{}) *SeatRepository_Decrement_Call {
	return &SeatRepository_Decrement_Call{Call: _e.mock.On("Decrement", ctx, eventID)}
}

func (_c *SeatRepository_Decrement_Call) Run(run func(ctx context.Context, eventID int64)) *SeatRepository_Decrement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SeatRepository_Decrement_Call) Return(n int64, err error) *SeatRepository_Decrement_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *SeatRepository_Decrement_Call) RunAndReturn(run func(ctx context.Context, eventID int64) (int64, error)) *SeatRepository_Decrement_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooked provides a mock function for the type SeatRepository
func (_mock *SeatRepository) GetBooked(ctx context.Context, eventID int64) (int64, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooked")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SeatRepository_GetBooked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooked'
type SeatRepository_GetBooked_Call struct {
	*mock.Call
}

// GetBooked is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
func (_e *SeatRepository_Expecter) GetBooked(ctx interface{}, eventID interface{}) *SeatRepository_GetBooked_Call {
	return &SeatRepository_GetBooked_Call{Call: _e.mock.On("GetBooked", ctx, eventID)}
}

func (_c *SeatRepository_GetBooked_Call) Run(run func(ctx context.Context, eventID int64)) *SeatRepository_GetBooked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SeatRepository_GetBooked_Call) Return(n int64, err error) *SeatRepository_GetBooked_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *SeatRepository_GetBooked_Call) RunAndReturn(run func(ctx context.Context, eventID int64) (int64, error)) *SeatRepository_GetBooked_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventCache provides a mock function for the type SeatRepository
func (_mock *SeatRepository) GetEventCache(ctx context.Context, eventID int64) (*repository.CachedEvent, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetEventCache")
	}

	var r0 *repository.CachedEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*repository.CachedEvent, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *repository.CachedEvent); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.CachedEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SeatRepository_GetEventCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventCache'
type SeatRepository_GetEventCache_Call struct {
	*mock.Call
}

// GetEventCache is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
func (_e *SeatRepository_Expecter) GetEventCache(ctx interface{}, eventID interface{}) *SeatRepository_GetEventCache_Call {
	return &SeatRepository_GetEventCache_Call{Call: _e.mock.On("GetEventCache", ctx, eventID)}
}

func (_c *SeatRepository_GetEventCache_Call) Run(run func(ctx context.Context, eventID int64)) *SeatRepository_GetEventCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SeatRepository_GetEventCache_Call) Return(cachedEvent *repository.CachedEvent, err error) *SeatRepository_GetEventCache_Call {
	_c.Call.Return(cachedEvent, err)
	return _c
}

func (_c *SeatRepository_GetEventCache_Call) RunAndReturn(run func(ctx context.Context, eventID int64) (*repository.CachedEvent, error)) *SeatRepository_GetEventCache_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function for the type SeatRepository
func (_mock *SeatRepository) Increment(ctx context.Context, eventID int64) error {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SeatRepository_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type SeatRepository_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
func (_e *SeatRepository_Expecter) Increment(ctx interface{}, eventID interface{}) *SeatRepository_Increment_Call {
	return &SeatRepository_Increment_Call{Call: _e.mock.On("Increment", ctx, eventID)}
}

func (_c *SeatRepository_Increment_Call) Run(run func(ctx context.Context, eventID int64)) *SeatRepository_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SeatRepository_Increment_Call) Return(err error) *SeatRepository_Increment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SeatRepository_Increment_Call) RunAndReturn(run func(ctx context.Context, eventID int64) error) *SeatRepository_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementBooked provides a mock function for the type SeatRepository
func (_mock *SeatRepository) IncrementBooked(ctx context.Context, eventID int64) error {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementBooked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SeatRepository_IncrementBooked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementBooked'
type SeatRepository_IncrementBooked_Call struct {
	*mock.Call
}

// IncrementBooked is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
func (_e *SeatRepository_Expecter) IncrementBooked(ctx interface{}, eventID interface{}) *SeatRepository_IncrementBooked_Call {
	return &SeatRepository_IncrementBooked_Call{Call: _e.mock.On("IncrementBooked", ctx, eventID)}
}

func (_c *SeatRepository_IncrementBooked_Call) Run(run func(ctx context.Context, eventID int64)) *SeatRepository_IncrementBooked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SeatRepository_IncrementBooked_Call) Return(err error) *SeatRepository_IncrementBooked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SeatRepository_IncrementBooked_Call) RunAndReturn(run func(ctx context.Context, eventID int64) error) *SeatRepository_IncrementBooked_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type SeatRepository
func (_mock *SeatRepository) Init(ctx context.Context, eventID int64, available int32) error {
	ret := _mock.Called(ctx, eventID, available)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int32) error); ok {
		r0 = returnFunc(ctx, eventID, available)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SeatRepository_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type SeatRepository_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
//   - available int32
func (_e *SeatRepository_Expecter) Init(ctx interface{}, eventID interface{}, available interface{}) *SeatRepository_Init_Call {
	return &SeatRepository_Init_Call{Call: _e.mock.On("Init", ctx, eventID, available)}
}

func (_c *SeatRepository_Init_Call) Run(run func(ctx context.Context, eventID int64, available int32)) *SeatRepository_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SeatRepository_Init_Call) Return(err error) *SeatRepository_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SeatRepository_Init_Call) RunAndReturn(run func(ctx context.Context, eventID int64, available int32) error) *SeatRepository_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Remaining provides a mock function for the type SeatRepository
func (_mock *SeatRepository) Remaining(ctx context.Context, eventID int64) (int64, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for Remaining")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SeatRepository_Remaining_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remaining'
type SeatRepository_Remaining_Call struct {
	*mock.Call
}

// Remaining is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
func (_e *SeatRepository_Expecter) Remaining(ctx interface{}, eventID interface{}) *SeatRepository_Remaining_Call {
	return &SeatRepository_Remaining_Call{Call: _e.mock.On("Remaining", ctx, eventID)}
}

func (_c *SeatRepository_Remaining_Call) Run(run func(ctx context.Context, eventID int64)) *SeatRepository_Remaining_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SeatRepository_Remaining_Call) Return(n int64, err error) *SeatRepository_Remaining_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *SeatRepository_Remaining_Call) RunAndReturn(run func(ctx context.Context, eventID int64) (int64, error)) *SeatRepository_Remaining_Call {
	_c.Call.Return(run)
	return _c
}

// SetBooked provides a mock function for the type SeatRepository
func (_mock *SeatRepository) SetBooked(ctx context.Context, eventID int64, booked int64) error {
	ret := _mock.Called(ctx, eventID, booked)

	if len(ret) == 0 {
		panic("no return value specified for SetBooked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, eventID, booked)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SeatRepository_SetBooked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBooked'
type SeatRepository_SetBooked_Call struct {
	*mock.Call
}

// SetBooked is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
//   - booked int64
func (_e *SeatRepository_Expecter) SetBooked(ctx interface{}, eventID interface{}, booked interface{}) *SeatRepository_SetBooked_Call {
	return &SeatRepository_SetBooked_Call{Call: _e.mock.On("SetBooked", ctx, eventID, booked)}
}

func (_c *SeatRepository_SetBooked_Call) Run(run func(ctx context.Context, eventID int64, booked int64)) *SeatRepository_SetBooked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SeatRepository_SetBooked_Call) Return(err error) *SeatRepository_SetBooked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SeatRepository_SetBooked_Call) RunAndReturn(run func(ctx context.Context, eventID int64, booked int64) error) *SeatRepository_SetBooked_Call {
	_c.Call.Return(run)
	return _c
}

// SetEventCache provides a mock function for the type SeatRepository
func (_mock *SeatRepository) SetEventCache(ctx context.Context, event *repository.CachedEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SetEventCache")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.CachedEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SeatRepository_SetEventCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEventCache'
type SeatRepository_SetEventCache_Call struct {
	*mock.Call
}

// SetEventCache is a helper method to define mock.On call
//   - ctx context.Context
//   - event *repository.CachedEvent
func (_e *SeatRepository_Expecter) SetEventCache(ctx interface{}, event interface{}) *SeatRepository_SetEventCache_Call {
	return &SeatRepository_SetEventCache_Call{Call: _e.mock.On("SetEventCache", ctx, event)}
}

func (_c *SeatRepository_SetEventCache_Call) Run(run func(ctx context.Context, event *repository.CachedEvent)) *SeatRepository_SetEventCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repository.CachedEvent
		if args[1] != nil {
			arg1 = args[1].(*repository.CachedEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SeatRepository_SetEventCache_Call) Return(err error) *SeatRepository_SetEventCache_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SeatRepository_SetEventCache_Call) RunAndReturn(run func(ctx context.Context, event *repository.CachedEvent) error) *SeatRepository_SetEventCache_Call {
	_c.Call.Return(run)
	return _c
}
