// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"booking-service/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewWaitlistRepository creates a new instance of WaitlistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWaitlistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WaitlistRepository {
	mock := &WaitlistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WaitlistRepository is an autogenerated mock type for the WaitlistRepository type
type WaitlistRepository struct {
	mock.Mock
}

type WaitlistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WaitlistRepository) EXPECT() *WaitlistRepository_Expecter {
	return &WaitlistRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type WaitlistRepository
func (_mock *WaitlistRepository) Add(entry *model.WaitlistEntry) error {
	ret := _mock.Called(entry)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.WaitlistEntry) error); ok {
		r0 = returnFunc(entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WaitlistRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type WaitlistRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - entry *model.WaitlistEntry
func (_e *WaitlistRepository_Expecter) Add(entry interface{}) *WaitlistRepository_Add_Call {
	return &WaitlistRepository_Add_Call{Call: _e.mock.On("Add", entry)}
}

func (_c *WaitlistRepository_Add_Call) Run(run func(entry *model.WaitlistEntry)) *WaitlistRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.WaitlistEntry
		if args[0] != nil {
			arg0 = args[0].(*model.WaitlistEntry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WaitlistRepository_Add_Call) Return(err error) *WaitlistRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WaitlistRepository_Add_Call) RunAndReturn(run func(entry *model.WaitlistEntry) error) *WaitlistRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// CountWaiting provides a mock function for the type WaitlistRepository
func (_mock *WaitlistRepository) CountWaiting(eventID int64) (int32, error) {
	ret := _mock.Called(eventID)

	if len(ret) == 0 {
		panic("no return value specified for CountWaiting")
	}

	var r0 int32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (int32, error)); ok {
		return returnFunc(eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) int32); ok {
		r0 = returnFunc(eventID)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaitlistRepository_CountWaiting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountWaiting'
type WaitlistRepository_CountWaiting_Call struct {
	*mock.Call
}

// CountWaiting is a helper method to define mock.On call
//   - eventID int64
func (_e *WaitlistRepository_Expecter) CountWaiting(eventID interface{}) *WaitlistRepository_CountWaiting_Call {
	return &WaitlistRepository_CountWaiting_Call{Call: _e.mock.On("CountWaiting", eventID)}
}

func (_c *WaitlistRepository_CountWaiting_Call) Run(run func(eventID int64)) *WaitlistRepository_CountWaiting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WaitlistRepository_CountWaiting_Call) Return(n int32, err error) *WaitlistRepository_CountWaiting_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *WaitlistRepository_CountWaiting_Call) RunAndReturn(run func(eventID int64) (int32, error)) *WaitlistRepository_CountWaiting_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEventAndUser provides a mock function for the type WaitlistRepository
func (_mock *WaitlistRepository) ExistsByEventAndUser(eventID int64, uid uuid.UUID) (bool, error) {
	ret := _mock.Called(eventID, uid)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEventAndUser")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, uuid.UUID) (bool, error)); ok {
		return returnFunc(eventID, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, uuid.UUID) bool); ok {
		r0 = returnFunc(eventID, uid)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, uuid.UUID) error); ok {
		r1 = returnFunc(eventID, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaitlistRepository_ExistsByEventAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEventAndUser'
type WaitlistRepository_ExistsByEventAndUser_Call struct {
	*mock.Call
}

// ExistsByEventAndUser is a helper method to define mock.On call
//   - eventID int64
//   - uid uuid.UUID
func (_e *WaitlistRepository_Expecter) ExistsByEventAndUser(eventID interface{}, uid interface{}) *WaitlistRepository_ExistsByEventAndUser_Call {
	return &WaitlistRepository_ExistsByEventAndUser_Call{Call: _e.mock.On("ExistsByEventAndUser", eventID, uid)}
}

func (_c *WaitlistRepository_ExistsByEventAndUser_Call) Run(run func(eventID int64, uid uuid.UUID)) *WaitlistRepository_ExistsByEventAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WaitlistRepository_ExistsByEventAndUser_Call) Return(b bool, err error) *WaitlistRepository_ExistsByEventAndUser_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *WaitlistRepository_ExistsByEventAndUser_Call) RunAndReturn(run func(eventID int64, uid uuid.UUID) (bool, error)) *WaitlistRepository_ExistsByEventAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetPositionByUser provides a mock function for the type WaitlistRepository
func (_mock *WaitlistRepository) GetPositionByUser(eventID int64, uid uuid.UUID) (int32, error) {
	ret := _mock.Called(eventID, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetPositionByUser")
	}

	var r0 int32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, uuid.UUID) (int32, error)); ok {
		return returnFunc(eventID, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, uuid.UUID) int32); ok {
		r0 = returnFunc(eventID, uid)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, uuid.UUID) error); ok {
		r1 = returnFunc(eventID, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaitlistRepository_GetPositionByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPositionByUser'
type WaitlistRepository_GetPositionByUser_Call struct {
	*mock.Call
}

// GetPositionByUser is a helper method to define mock.On call
//   - eventID int64
//   - uid uuid.UUID
func (_e *WaitlistRepository_Expecter) GetPositionByUser(eventID interface{}, uid interface{}) *WaitlistRepository_GetPositionByUser_Call {
	return &WaitlistRepository_GetPositionByUser_Call{Call: _e.mock.On("GetPositionByUser", eventID, uid)}
}

func (_c *WaitlistRepository_GetPositionByUser_Call) Run(run func(eventID int64, uid uuid.UUID)) *WaitlistRepository_GetPositionByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WaitlistRepository_GetPositionByUser_Call) Return(n int32, err error) *WaitlistRepository_GetPositionByUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *WaitlistRepository_GetPositionByUser_Call) RunAndReturn(run func(eventID int64, uid uuid.UUID) (int32, error)) *WaitlistRepository_GetPositionByUser_Call {
	_c.Call.Return(run)
	return _c
}
